### ISSUE TITLE
piping ecr login 

### ISSUE THREAD

**Issue by syedfahimabrar** [TapTap21/docker-remote-deployment-action#3]
Can we pipe this with amazon ecr as we already logged in with that action?

here is the link: https://github.com/aws-actions/amazon-ecr-login

**Comment by TapTap21** [comment]
Thanks for the issue @syedfahimabrar 

The login in this action is performed via docker context. This means that the login is actually performed on the machine being deployed to and not the runner using the action.  Thus this won't be possible as the images are pulled to the target machine and that machine has to be authenticated to do so.
